before_install:
    - git config --global user.email "sdamiano@stroudcenter.org"
    - git config --global user.name "SRGDamia1"

sudo: false
git:
  depth: 1
  sparse_checkout: travis_sparse_checkout
cache:
    pip: true
    directories:
        - "~/.platformio"
language: python
python:
    - "2.7"
install:
    # Remove the cloned repo to emulate a user library installation
    - git rm library.json
    # - git rm library.properties
    # - git rm -r pioScripts
    # - git rm -r src
    # Install PlatformIO (this should be cached!)
    - pip install -U platformio
    - pio upgrade
    # Uninstall any old version of the current library from the Travis cache
    - if pio lib -g uninstall EnviroDIY_ModularSensors; then
        echo "Uninstalled cached version of ModularSensors";
      fi
    # Install this library from the branch we're working on
    # echo "Installing ModularSensors from https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH";
    # echo "Installing ModularSensors from https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_BRANCH";
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "Installing ModularSensors from https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_COMMIT";
      else
        echo "Installing ModularSensors from https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_SHA";
      fi
    # pio lib -g install https://github.com/$TRAVIS_REPO_SLUG.git#$BRANCH;
    # pio lib -g install https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_BRANCH;
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        pio lib -g install https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_COMMIT;
      else
        pio lib -g install https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_SHA;
      fi
    - pio update
script:
    - platformio ci --project-option="lib_ldf_mode = deep+" --board=mayfly  --board=megaatmega2560 --board=adafruit_feather_m0  --board=sodaq_autonomo

matrix:
    include:
      - language: node_js
        install: npm install -g jsonlint
        script: jsonlint -q library.json

      - env:
          - PLATFORMIO_CI_SRC=examples/single_sensor/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/multisensor_print/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/simple_logging/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/DRWI_CitSci/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/DRWI_NoCellular/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/double_logger/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/baro_rho_correction/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/data_saving/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
      - env:
          - PLATFORMIO_CI_SRC=examples/logging_to_ThingSpeak/
          - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT -D MQTT_MAX_PACKET_SIZE=240"

      - env:
        - PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY_Zero/
        - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"

      - env:
        - PLATFORMIO_CI_SRC=compile_tests/AVR_all_sensors/
        - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
        script:
          # Install serial libraries
          - pio lib -g install https://github.com/PaulStoffregen/AltSoftSerial.git
          - pio lib -g install https://github.com/EnviroDIY/SoftwaterSerial_ExternalInts.git
          - platformio ci --project-option="lib_ldf_mode = deep+" --board=mayfly
          # Uninstall serial libraries so they don't cache and mess up the SAMD compiler
          - pio lib -g uninstall AltSoftSerial
          - pio lib -g uninstall SoftwaterSerial_ExternalInts

      - env:
        - PLATFORMIO_CI_SRC=compile_tests/SAMD_all_sensors/
        - PLATFORMIO_BUILD_FLAGS="-D SDI12_EXTERNAL_PCINT"
        script:
          - platformio ci --project-option="lib_ldf_mode = deep+" --board=adafruit_feather_m0
