language: python
python:
    - "2.7"
sudo: false
git:
  depth: 1
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/multisensor_print/
    - PLATFORMIO_CI_SRC=examples/simple_logging/
    - PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY/
before_install:
- git config --global user.email "sdamiano@stroudcenter.org"
- git config --global user.name "SRGDamia1"
install:
    - pip install -U platformio
    - pio upgrade
    - pio update
    - pio lib -g install https://github.com/EnviroDIY/Sodaq_DS3231.git
    - pio lib -g install https://github.com/SodaqMoja/RTCTimer
    - pio lib -g install https://github.com/EnviroDIY/PcInt_PCINT0.git
    - pio lib -g install https://github.com/EnviroDIY/SdFat.git
    - pio lib -g install https://github.com/EnviroDIY/SoftwareSerial_PCINT12.git
    - pio lib -g install https://github.com/Adafruit/Adafruit_ADS1X15.git
    - pio lib -g install https://github.com/EnviroDIY/Arduino-SDI-12.git#mayfly
    - pio lib -g install https://github.com/EnviroDIY/GPRSbee.git
    - pio lib -g update
script:
- platformio ci --lib="." --project-option="lib_ldf_mode = deep+" --board=mayfly
