language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/multisensor_print/

install:
    - pip install -U platformio
    - pio upgrade
    - pio update
    - git clone --depth 1 https://github.com/EnviroDIY/Libraries.git EnviroDIYLibs

script:
    - platformio ci --lib="." --board=mayfly --project-option="lib_extra_dirs=EnviroDIYLibs" --project-option="lib_ignore=EnviroDIY_ModularSensors"
