language: python
python:
    - "2.7"
sudo: false
git:
  depth: 1
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/multisensor_print/
    - PLATFORMIO_CI_SRC=examples/simple_logging/
    - PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY/
before_install:
- git config --global user.email "sdamiano@stroudcenter.org"
- git config --global user.name "SRGDamia1"
install:
    - pip install -U platformio
    - pio upgrade
    - pio update
    - pio lib -g install EnviroDIYLibs=https://github.com/EnviroDIY/Libraries.git
    - rm -rf ../../../../../home/travis/.platformio/lib/EnviroDIYLibs/EnviroDIY_ModularSensors
    - pio lib -g uninstall EnviroDIY_ModularSensors
script:
- platformio ci --lib="." --project-option="lib_extra_dirs=../../../../../home/travis/.platformio/lib/EnviroDIYLibs" --project-option="lib_ldf_mode = deep+" --board=mayfly
