before_install:
    - git config --global user.email "sdamiano@stroudcenter.org"
    - git config --global user.name "SRGDamia1"

sudo: false
git:
  depth: 1
cache:
    directories:
        - "~/.platformio"
language: python
python:
    - "2.7"
install:
    # Remove the cloned repo to emulate a user library installation
    - git rm library.json
    - git rm library.properties
    - git rm -r pioScripts
    - git rm -r src
    # Install PlatformIO (this should be cached!)
    - pip install -U platformio
    - pio upgrade
    # Uninstall any old version of the current library from the Travis cache
    - pio lib uninstall EnviroDIY_ModularSensors
    # Get the current branch
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
    # Install this library from the branch we're working on
    - pio lib -g install https://github.com/EnviroDIY/ModularSensors.git#$BRANCH
    # Install serial libraries needed for most examples
    - pio lib -g install https://github.com/PaulStoffregen/AltSoftSerial.git  # #73, but need the git until Paul S. has a new release
    - pio lib -g install https://github.com/EnviroDIY/SoftwaterSerial_ExternalInts.git
    - pio update
script:
    - platformio ci -v --project-option="lib_ignore = RTCZero"  --project-option="lib_ldf_mode = deep+" --board=mayfly

matrix:
    include:
      - language: node_js
        install: npm install -g jsonlint
        script: jsonlint -q library.json

      - env: PLATFORMIO_CI_SRC=examples/single_sensor/
      - env: PLATFORMIO_CI_SRC=examples/multisensor_print/
      - env: PLATFORMIO_CI_SRC=examples/simple_logging/
      - env: PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY/
      - env: PLATFORMIO_CI_SRC=examples/DRWI_CitSci/
      - env: PLATFORMIO_CI_SRC=examples/DRWI_NoCellular/
      - env: PLATFORMIO_CI_SRC=examples/double_logger/
      - env: PLATFORMIO_CI_SRC=examples/baro_rho_correction/
      - env: PLATFORMIO_CI_SRC=examples/data_saving/

      - env: PLATFORMIO_CI_SRC=examples/logging_to_EnviroDIY_Zero/
        script:
            - platformio ci -v --project-option="lib_ignore = SoftwareSerial_ExtInts, AltSoftSerial, SoftI2CMaster"  --project-option="lib_ldf_mode = deep+" --board=adafruit_feather_m0
