language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/multisensor_print/

install:
    - pip install -U platformio
    - pio upgrade
    - pio update

script:
    - platformio ci --lib="." --project-conf=platformio.ini
