name: Build Examples with Arduino CLI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        example:
          [
            examples/single_sensor/,
            examples/simple_logging/,
            examples/simple_logging_LearnEnviroDIY/,
            examples/DRWI_CitSci/,
            examples/DRWI_LTE/,
            examples/DRWI_NoCellular/,
            examples/double_logger/,
            examples/baro_rho_correction/,
            examples/data_saving/,
            examples/logging_to_MMW/,
            examples/logging_to_ThingSpeak/,
          ]
        # arduino-platform: ['EnviroDIY:avr', 'arduino:avr', 'arduino:samd', 'adafruit:samd']
        fqbn: ['EnviroDIY:avr:envirodiy_mayfly']
        include:
          - fqbn: 'EnviroDIY:avr:envirodiy_mayfly'
            extra_build_flags: '-DNEOSWSERIAL_EXTERNAL_PCINT'
          - fqbn: 'arduino:avr:mega'
            extra_build_flags: '-DNEOSWSERIAL_EXTERNAL_PCINT'
          - fqbn: 'arduino:samd:mzero_bl'
            extra_build_flags: '-DNEOSWSERIAL_EXTERNAL_PCINT -DARDUINO_SAMD_ZERO -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x804d -DUSBCON'
          - fqbn: 'adafruit:samd:adafruit_feather_m0'
            extra_build_flags: '-DNEOSWSERIAL_EXTERNAL_PCINT -DARDUINO_SAMD_ZERO -DARM_MATH_CM0PLUS -DADAFRUIT_FEATHER_M0 -D__SAMD21G18A__ -DUSB_VID=0x239A -DUSB_PID=0x800B -DUSBCON -DUSB_CONFIG_POWER=100'
          - fqbn: 'SODAQ:samd:sodaq_autonomo'
            extra_build_flags: '-DNEOSWSERIAL_EXTERNAL_PCINT -DVERY_LOW_POWER -D__SAMD21J18A__ -DUSB_VID=0x2341 -DUSB_PID=0x804d -DUSBCON'

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          if [[ -z "${GITHUB_HEAD_REF}" ]]; then
            echo "::debug::Push to commit ${GITHUB_SHA}"
            echo "LIBRARY_INSTALL_ZIP=https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.zip" >> $GITHUB_ENV
          else
            echo "::debug::Pull Request from the ${GITHUB_HEAD_REF} branch"
            echo "LIBRARY_INSTALL_ZIP=https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_HEAD_REF}.zip" >> $GITHUB_ENV
          fi

      # We use the `arduino/setup-arduino-cli` action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Restore or Cache Arduino Platforms and Libraries
        uses: actions/cache@v2.1.5
        id: cache_arduino
        with:
          path: home/arduino
          # if nothing in the dependencies.json file has changed, then it will
          # be a "cache hit" and we can restore libraries from cache and not
          # download them.  If it has changed we have to re-download.
          key: ${{ hashFiles('./dependencies.json') }}

      # Install cores and library dependencies for the Arduino CLI, iff no cache
      - name: Install the Arduino libraries
        if: steps.cache_arduino.outputs.cache-hit != 'true'
        run: |
          chmod +x continuous_integration/install-deps-arduino-cli.sh
          sh continuous_integration/install-deps-arduino-cli.sh

      # Install ModularSensors for the Arduino CLI
      - name: Install the testing version of Modular Sensors
        run: |
          curl -L ${{ env.LIBRARY_INSTALL_ZIP }} --create-dirs -o home/arduino/downloads/ModularSensors.zip
          unzip -q -o home/arduino/downloads/ModularSensors.zip -d home/arduino/downloads/ -x "*.git/*" "continuous_integration/*" "docs/*" "examples/*"
          mkdir -p home/arduino/user/libraries/ModularSensors
          mv home/arduino/downloads/ModularSensors-${GITHUB_SHA}/* home/arduino/user/libraries/ModularSensors
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib update-index
          arduino-cli --config-file continuous_integration/arduino_cli.yaml lib list
          ls home/arduino/user/libraries

      - name: Compile examples using the Arduino CLI
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          EXTRA_BUILD_FLAGS: ${{ extra_build_flags }}
        run: |
          arduino-cli --config-file continuous_integration/arduino_cli.yaml compile --clean --build-property "build.extra_flags=$EXTRA_BUILD_FLAGS" --fqbn ${{ matrix.fqbn }} ${{ matrix.example }}

      - name: Uninstall testing version of Modular Sensors before caching
        run: arduino-cli --config-file continuous_integration/arduino_cli.yaml lib uninstall EnviroDIY_ModularSensors
