name: Build Examples

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        example:
          [
            examples/single_sensor/,
            examples/simple_logging/,
            examples/DRWI_CitSci/,
            examples/DRWI_LTE/,
            examples/DRWI_NoCellular/,
            examples/double_logger/,
            examples/baro_rho_correction/,
            examples/data_saving/,
            examples/logging_to_ThingSpeak/,
            examples/menu_a_la_carte/,
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Restore or Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # if requirements.txt hasn't changed, then it will be a "cache hit" and pip will be restored
          # if requirements.txt HAS changed, it will be a "cache miss" and a new cache of pip will be created if the job completes successfully
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Restore or Cache PlatformIO and Libraries
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          # if nothing in the lock files has changed, then it will be a "cache hit" and pip will be restored
          # otherwise, it will be a "cache miss" and a new cache of libraries will be created if the job completes successfully
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      # This should be pulled from cache, if there's not a new version
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      # Install *all* the dependencies!
      - name: Install the dependencies at global level
        run: |
          pio lib -g install envirodiy/EnviroDIY_DS3231
          pio lib -g install arduino-libraries/RTCZero
          pio lib -g install greygnome/EnableInterrupt
          pio lib -g install greiman/SdFat
          pio lib -g install vshymanskyy/TinyGSM
          pio lib -g install knolleary/PubSubClient
          pio lib -g install adafruit/'Adafruit BusIO'
          pio lib -g install adafruit/'Adafruit Unified Sensor'
          pio lib -g install https://github.com/soligen2010/Adafruit_ADS1X15.git
          pio lib -g install adafruit/'Adafruit AM2315'
          pio lib -g install adafruit/'Adafruit BME280 Library'
          pio lib -g install adafruit/'DHT sensor library'
          pio lib -g install adafruit/'Adafruit INA219'
          pio lib -g install adafruit/'Adafruit MPL115A2'
          pio lib -g install paulstoffregen/OneWire
          pio lib -g install milesburton/DallasTemperature
          pio lib -g install envirodiy/SDI-12
          pio lib -g install northernwidget/MS5803
          pio lib -g install https://github.com/NorthernWidget-Skunkworks/Tally_Library.git#Dev_I2C
          pio lib -g install envirodiy/SensorModbusMaster
          pio lib -g install envirodiy/KellerModbus
          pio lib -g install envirodiy/YosemitechModbus
          pio lib -g install vshymanskyy/StreamDebugger
          pio lib -g install https://github.com/EnviroDIY/SoftwareSerial_ExternalInts.git
          pio lib -g install https://github.com/PaulStoffregen/AltSoftSerial.git
          pio lib -g install https://github.com/SRGDamia1/NeoSWSerial.git
          pio lib -g install https://github.com/Testato/SoftwareWire.git

      - name: Update Libraries from Cache
        run: pio lib -g update

      # # We want to install from exactly the point that we're working on
      # # NOTE:  We do NOT install to the global directory so it's not cached!
      # - name: Install ModularSensors as current state
      #   run: |
      #     ls
      #     mkdir -p ${{ github.workspace }}/lib
      #     ls
      #     pio lib -d ${{ github.workspace }}/lib install https://github.com/${{ github.repository }}.git#$GITHUB_SHA

      - name: Run PlatformIO
        run: platformio ci --project-conf="continuous_integration/platformio.ini"
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

      - name: List libraries
        run: |
          pio lib list
          pio lib -g list
